site_name: Jacob Istio & Service Mesh E-Book
site_description: "Jacob's Istio & Service Mesh Tutorial"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxistiobook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '第一章: 微服务和 Service Mesh 核心组件':
    - '第一节 Service Mesh 学习与架构分析': 'chap1/1chap1_learn_SM.md'
    - '第二节 服务注册中心': 'chap1/2chap1_service_register.md'
    - '第三节 负载均衡器': 'chap1/3chap1_load_balancer.md'
    - '第四节 路由器及其限流熔断路由策略': 'chap1/4chap1_router.md'
    - '第五节 连接池：阻塞式连接池和多路复用连接池的差异': 'chap1/5chap1_conn_pool.md'
    - '第六节 微服务网关（Kong）：网关在微服务架构中的作用': 'chap1/6chap1_apigateway_kong.md'
    - '第七节 微服务治理的配置中心': 'chap1/7chap1_config_center.md'
  - '第四章: Istio(1.10.3)-Bookinfo 流量管理':
    - '第一节 2021 Service Mesh & Istio 介绍/安装(1.10.3)': 'chap4/1Istio_Intro.md'
    - '第二节 使用 Istio 实现非侵入流量治理': 'chap4/2Istio_flow_control.md'
    - '第三节 Istio 流量管理之故障注入': 'chap4/3Istio_fault_inject.md'
   
    
repo_url: https://github.com/Chao-Xi/jxistiobook.git
repo_name: "jxistiobook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.jpeg'
  favicon: 'images/logo.jpeg'
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'
