site_name: Jacob Istio & Service Mesh E-Book
site_description: "Jacob's Istio & Service Mesh Tutorial"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxistiobook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '第一章: 微服务和 Service Mesh 核心组件':
    - '第一节 Service Mesh 学习与架构分析': 'chap1/1chap1_learn_SM.md'
    - '第二节 服务注册中心': 'chap1/2chap1_service_register.md'
    - '第三节 负载均衡器': 'chap1/3chap1_load_balancer.md'
    - '第四节 路由器及其限流熔断路由策略': 'chap1/4chap1_router.md'
    - '第五节 连接池：阻塞式连接池和多路复用连接池的差异': 'chap1/5chap1_conn_pool.md'
    - '第六节 微服务网关（Kong）：网关在微服务架构中的作用': 'chap1/6chap1_apigateway_kong.md'
    - '第七节 微服务治理的配置中心': 'chap1/7chap1_config_center.md'
    - '第八节 Trace 更快速定位问题': 'chap1/8chap1_trace.md'
    - '第九节 利用 Prometheus 和 Grafana 收集监控数据': 'chap1/9chap1_monitor.md'
  - '第二章: Service Mesh 实战':
    - '第一节 Service Mesh 开源产品中的技术选型': 'chap2/1chap2_sm_prods.md'
    - '第二节 最常用的数据面 Envoy介绍': 'chap2/2chap2_sm_envoy.md'
    - '第三节 Istio 入门：基于最新 1.7 版本的环境搭建和介绍': 'chap2/3chap3_isitio_17.md'
    - '第四节 xDS：控制面和数据面的通信桥梁': 'chap2/4chap3_xds.md'
    - '第五节 Ingress 和 Egress：入口流量和出口流量控制': 'chap2/5chap3_ingress_egress.md'
    - '第六节 金丝雀发布：金丝雀部署和版本控制': 'chap2/6chap3_canary.md'
    - '第七节 如何利用组件做到服务的可观测性': 'chap2/7chap3_monitor.md'
    - '第八节 Proj项目落地: Go 实现 Service Mesh': 'chap2/8chap3_SM_GO_PROJ.md'
    - '第九节 Service Mesh 落地和展望': 'chap2/9chap3_pratice.md'
    - '第十节 Mesh的未来发展与可行性方向': 'chap2/10chap3_mesh.md'
  - '第三章: Istio基础教学':
    - '第一节 服务网格(Service Mesh)是什么?': 'chap3/0Service_Mesh.md'
    - '第二节 Istio 架构与技术': 'chap3/1isba_Frame_Tech.md'
    - '第三节 Istio 服务发现和 Pilot的架构机制': 'chap3/2isba_Service_Find.md'
    - '第四节 Gateway 设计与实现': 'chap3/3isba_Gateway.md'
    - '第五节 Istio 灰度发布与技术实现': 'chap3/4isba_Gray_release.md'
    - '第六节 xDS协议解析': 'chap3/5isba_Xds.md'
    - '第七节 Mixer基础与实现': 'chap3/6isba_Mixer.md'
  - '第四章: Istio(1.10.3)-Bookinfo 流量管理':
    - '第一节 2021 Service Mesh & Istio 介绍/安装(1.10.3)': 'chap4/1Istio_Intro.md'
    - '第二节 使用 Istio 实现非侵入流量治理': 'chap4/2Istio_flow_control.md'
    - '第三节 Istio 流量管理之故障注入': 'chap4/3Istio_fault_inject.md'
    - '第四节 Istio ServiceEntry 的填坑之路': 'chap4/4Istio_ServiceEntry_issue.md'
  - '第五章: Istio 高级教学与实践':
    - '第一节 服务网格的基本特征': 'chap5/1Service_Mesh_Intro.md'
    - '第二节 Istio 基本介绍': 'chap5/2Istio_Intro.md'
    - '第三节 Istio, Service Mesh 快速入门（Istio 1.1.16）': 'chap5/3Istro_ServiceM_Prac.md'
    - '第四节 用Helm部署Istio': 'chap5/4Istio_Helm.md'
    - '第五节 Istio 常用功能 （自动/手动部署Istio应用）': 'chap5/5Istio_funcs.md'
    - '第六节 使用 Istio Dashboard Grafana / Prometheus': 'chap5/6Istio_func2_grafana_prometheus.md'
    - '第七节 使用 Istio Dashboard': 'chap5/7Istio_fun3_Jager.md'
    - '第八节 使用Kiali': 'chap5/8Istio_func4_Kiali.md'
    - '第九节 HTTPS流量管理(目标规则/默认路由/流量的拆分和迁移)': 'chap5/9Istio_http1.md'
    - '第十节 HTTPS流量管理(金丝雀部署/源服务进行路由/URI进行重定向)': 'chap5/10Istio_http2.md'
    - '第十一节 HTTPS流量管理（通信超时/故障重试/入口~出口流量管理）': 'chap5/11Istio_http3.md'
    - '第十二节 HTTPS流量管理（服务熔断/故障注入测试/注入中断/流量复制)': 'chap5/12Istio_http4.md'
    - '第十三节 Mixer 适配器的应用(简介/Denier访问控制/Listchecker访问控制)': 'chap5/13Istio_Mixer1.md'
    - '第十四节 Mixer 适配器的应用(MemQuota服务限流/Mixer对象的定义/RedisQuota服务限流)': 'chap5/14Istio_Mixer2.md'
    - '第十五节 Mixer 适配器的应用 - 为Prometheus定义监控指标': 'chap5/15Istio_Mixer3_prometheus.md'
    - '第十六节 使用stdio输出自定义日志': 'chap5/16Istio_Mixer4_stdio.md'
    - '第十七节 使用Fluentd输出日志': 'chap5/17Istio_Mixer5_fluentd.md'
    - '第十八节 Istio的安全加固（启用mTLS\加固概述)': 'chap5/18Istio_Sec1.md'
    - '第十九节 Istio的安全加固(RBAC设置\拍错）': 'chap5/19Istio_Sec2_RBAC.md'
    - '第二十节 Istio的试用建议': 'chap5/20Istio_Usage.md'
  - '第六章: 实验与教学bookinfo(istio-1.3)':
    - 'L1 Docker for Mac安装istio(istio-1.3)': 'chap6/1Istio_install_docker.md'
    - 'L2 基于Bookinfo的流量管理配置(服务版本/基于权重/基于请求内容)': 'chap6/2BookInfo_1.md'
    - 'L3 基于Bookinfo的流量管理配置(延迟访问/中断访问/不同环境/服务网格外)': 'chap6/3BookInfo_2.md'
  - '第七章: JenkinsX + Istio渐进式交付':
    - 'L1 Kubernetes中的渐进式交付:蓝绿部署和金丝雀部署shipper/Istio/Flagger': 'chap7/k8s_adv54_release.md'
    - 'L2 使用 Jenkins X 渐进式交付': 'chap7/k8s_adv56_jenkinsX.md'
    - 'L3 使用 Jenkins X 渐进式交付:自动化金丝雀部署': 'chap7/k8s_adv57_Auto_Canary.md'

repo_url: https://github.com/Chao-Xi/jxistiobook.git
repo_name: "jxistiobook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.jpeg'
  favicon: 'images/logo.jpeg'
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'
