site_name: Jacob Istio & Service Mesh E-Book
site_description: "Jacob's Istio & Service Mesh Tutorial"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: https://chao-xi.github.io/jxistiobook/

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '第一章: 微服务和 Service Mesh 核心组件':
    - '第一节 Service Mesh 学习与架构分析': 'chap1/1chap1_learn_SM.md'
    - '第二节 服务注册中心': 'chap1/2chap1_service_register.md'
    - '第三节 负载均衡器': 'chap1/3chap1_load_balancer.md'
    - '第四节 路由器及其限流熔断路由策略': 'chap1/4chap1_router.md'
    - '第五节 连接池：阻塞式连接池和多路复用连接池的差异': 'chap1/5chap1_conn_pool.md'
    - '第六节 微服务网关（Kong）：网关在微服务架构中的作用': 'chap1/6chap1_apigateway_kong.md'
    - '第七节 微服务治理的配置中心': 'chap1/7chap1_config_center.md'
    - '第八节 Trace 更快速定位问题': 'chap1/8chap1_trace.md'
    - '第九节 利用 Prometheus 和 Grafana 收集监控数据': 'chap1/9chap1_monitor.md'
  - '第二章: Service Mesh 实战':
    - '第一节 Service Mesh 开源产品中的技术选型': 'chap2/1chap2_sm_prods.md'
    - '第二节 最常用的数据面 Envoy介绍': 'chap2/2chap2_sm_envoy.md'
    - '第三节 Istio 入门：基于最新 1.7 版本的环境搭建和介绍': 'chap2/3chap3_isitio_17.md'
    - '第四节 xDS：控制面和数据面的通信桥梁': 'chap2/4chap3_xds.md'
    - '第五节 Ingress 和 Egress：入口流量和出口流量控制': 'chap2/5chap3_ingress_egress.md'
  - '第四章: Istio(1.10.3)-Bookinfo 流量管理':
    - '第一节 2021 Service Mesh & Istio 介绍/安装(1.10.3)': 'chap4/1Istio_Intro.md'
    - '第二节 使用 Istio 实现非侵入流量治理': 'chap4/2Istio_flow_control.md'
    - '第三节 Istio 流量管理之故障注入': 'chap4/3Istio_fault_inject.md'
   
    
repo_url: https://github.com/Chao-Xi/jxistiobook.git
repo_name: "jxistiobook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.jpeg'
  favicon: 'images/logo.jpeg'
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'
